### ISSUE TITLE
Allow executing custom commands

### ISSUE THREAD

**Issue by aequasi** [bruli/php-git-hooks#15]
I'd liek to be able to execute my own commands, instead of the specified few that are allowed.

**Comment by bruli** [comment]
Hi.

Could you write an example?

**Comment by aequasi** [comment]
```yml
pre-commit:
  enabled: true
  execute:
    custom:
      - ./bldr.phar run precommit
```
